/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
)

// checks if the ResponsesHyperlaneRemoteDomain type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesHyperlaneRemoteDomain{}

// ResponsesHyperlaneRemoteDomain struct for ResponsesHyperlaneRemoteDomain
type ResponsesHyperlaneRemoteDomain struct {
	ChainMetadata *ResponsesChainMetadata `json:"chain_metadata,omitempty"`
	RemoteDomain *int64 `json:"remote_domain,omitempty"`
}

// NewResponsesHyperlaneRemoteDomain instantiates a new ResponsesHyperlaneRemoteDomain object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesHyperlaneRemoteDomain() *ResponsesHyperlaneRemoteDomain {
	this := ResponsesHyperlaneRemoteDomain{}
	return &this
}

// NewResponsesHyperlaneRemoteDomainWithDefaults instantiates a new ResponsesHyperlaneRemoteDomain object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesHyperlaneRemoteDomainWithDefaults() *ResponsesHyperlaneRemoteDomain {
	this := ResponsesHyperlaneRemoteDomain{}
	return &this
}

// GetChainMetadata returns the ChainMetadata field value if set, zero value otherwise.
func (o *ResponsesHyperlaneRemoteDomain) GetChainMetadata() ResponsesChainMetadata {
	if o == nil || IsNil(o.ChainMetadata) {
		var ret ResponsesChainMetadata
		return ret
	}
	return *o.ChainMetadata
}

// GetChainMetadataOk returns a tuple with the ChainMetadata field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneRemoteDomain) GetChainMetadataOk() (*ResponsesChainMetadata, bool) {
	if o == nil || IsNil(o.ChainMetadata) {
		return nil, false
	}
	return o.ChainMetadata, true
}

// HasChainMetadata returns a boolean if a field has been set.
func (o *ResponsesHyperlaneRemoteDomain) HasChainMetadata() bool {
	if o != nil && !IsNil(o.ChainMetadata) {
		return true
	}

	return false
}

// SetChainMetadata gets a reference to the given ResponsesChainMetadata and assigns it to the ChainMetadata field.
func (o *ResponsesHyperlaneRemoteDomain) SetChainMetadata(v ResponsesChainMetadata) {
	o.ChainMetadata = &v
}

// GetRemoteDomain returns the RemoteDomain field value if set, zero value otherwise.
func (o *ResponsesHyperlaneRemoteDomain) GetRemoteDomain() int64 {
	if o == nil || IsNil(o.RemoteDomain) {
		var ret int64
		return ret
	}
	return *o.RemoteDomain
}

// GetRemoteDomainOk returns a tuple with the RemoteDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneRemoteDomain) GetRemoteDomainOk() (*int64, bool) {
	if o == nil || IsNil(o.RemoteDomain) {
		return nil, false
	}
	return o.RemoteDomain, true
}

// HasRemoteDomain returns a boolean if a field has been set.
func (o *ResponsesHyperlaneRemoteDomain) HasRemoteDomain() bool {
	if o != nil && !IsNil(o.RemoteDomain) {
		return true
	}

	return false
}

// SetRemoteDomain gets a reference to the given int64 and assigns it to the RemoteDomain field.
func (o *ResponsesHyperlaneRemoteDomain) SetRemoteDomain(v int64) {
	o.RemoteDomain = &v
}

func (o ResponsesHyperlaneRemoteDomain) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesHyperlaneRemoteDomain) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ChainMetadata) {
		toSerialize["chain_metadata"] = o.ChainMetadata
	}
	if !IsNil(o.RemoteDomain) {
		toSerialize["remote_domain"] = o.RemoteDomain
	}
	return toSerialize, nil
}

type NullableResponsesHyperlaneRemoteDomain struct {
	value *ResponsesHyperlaneRemoteDomain
	isSet bool
}

func (v NullableResponsesHyperlaneRemoteDomain) Get() *ResponsesHyperlaneRemoteDomain {
	return v.value
}

func (v *NullableResponsesHyperlaneRemoteDomain) Set(val *ResponsesHyperlaneRemoteDomain) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesHyperlaneRemoteDomain) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesHyperlaneRemoteDomain) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesHyperlaneRemoteDomain(val *ResponsesHyperlaneRemoteDomain) *NullableResponsesHyperlaneRemoteDomain {
	return &NullableResponsesHyperlaneRemoteDomain{value: val, isSet: true}
}

func (v NullableResponsesHyperlaneRemoteDomain) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesHyperlaneRemoteDomain) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


