/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
)

// checks if the ResponsesRollupProvider type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesRollupProvider{}

// ResponsesRollupProvider struct for ResponsesRollupProvider
type ResponsesRollupProvider struct {
	Address *string `json:"address,omitempty"`
	Namespace *string `json:"namespace,omitempty"`
}

// NewResponsesRollupProvider instantiates a new ResponsesRollupProvider object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesRollupProvider() *ResponsesRollupProvider {
	this := ResponsesRollupProvider{}
	return &this
}

// NewResponsesRollupProviderWithDefaults instantiates a new ResponsesRollupProvider object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesRollupProviderWithDefaults() *ResponsesRollupProvider {
	this := ResponsesRollupProvider{}
	return &this
}

// GetAddress returns the Address field value if set, zero value otherwise.
func (o *ResponsesRollupProvider) GetAddress() string {
	if o == nil || IsNil(o.Address) {
		var ret string
		return ret
	}
	return *o.Address
}

// GetAddressOk returns a tuple with the Address field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesRollupProvider) GetAddressOk() (*string, bool) {
	if o == nil || IsNil(o.Address) {
		return nil, false
	}
	return o.Address, true
}

// HasAddress returns a boolean if a field has been set.
func (o *ResponsesRollupProvider) HasAddress() bool {
	if o != nil && !IsNil(o.Address) {
		return true
	}

	return false
}

// SetAddress gets a reference to the given string and assigns it to the Address field.
func (o *ResponsesRollupProvider) SetAddress(v string) {
	o.Address = &v
}

// GetNamespace returns the Namespace field value if set, zero value otherwise.
func (o *ResponsesRollupProvider) GetNamespace() string {
	if o == nil || IsNil(o.Namespace) {
		var ret string
		return ret
	}
	return *o.Namespace
}

// GetNamespaceOk returns a tuple with the Namespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesRollupProvider) GetNamespaceOk() (*string, bool) {
	if o == nil || IsNil(o.Namespace) {
		return nil, false
	}
	return o.Namespace, true
}

// HasNamespace returns a boolean if a field has been set.
func (o *ResponsesRollupProvider) HasNamespace() bool {
	if o != nil && !IsNil(o.Namespace) {
		return true
	}

	return false
}

// SetNamespace gets a reference to the given string and assigns it to the Namespace field.
func (o *ResponsesRollupProvider) SetNamespace(v string) {
	o.Namespace = &v
}

func (o ResponsesRollupProvider) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesRollupProvider) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Address) {
		toSerialize["address"] = o.Address
	}
	if !IsNil(o.Namespace) {
		toSerialize["namespace"] = o.Namespace
	}
	return toSerialize, nil
}

type NullableResponsesRollupProvider struct {
	value *ResponsesRollupProvider
	isSet bool
}

func (v NullableResponsesRollupProvider) Get() *ResponsesRollupProvider {
	return v.value
}

func (v *NullableResponsesRollupProvider) Set(val *ResponsesRollupProvider) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesRollupProvider) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesRollupProvider) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesRollupProvider(val *ResponsesRollupProvider) *NullableResponsesRollupProvider {
	return &NullableResponsesRollupProvider{value: val, isSet: true}
}

func (v NullableResponsesRollupProvider) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesRollupProvider) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


