/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"os"
)

// checks if the ResponsesGasPayment type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesGasPayment{}

// ResponsesGasPayment struct for ResponsesGasPayment
type ResponsesGasPayment struct {
	Amount *string `json:"amount,omitempty"`
	GasAmount *string `json:"gas_amount,omitempty"`
	IgpId **os.File `json:"igp_id,omitempty"`
}

// NewResponsesGasPayment instantiates a new ResponsesGasPayment object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesGasPayment() *ResponsesGasPayment {
	this := ResponsesGasPayment{}
	return &this
}

// NewResponsesGasPaymentWithDefaults instantiates a new ResponsesGasPayment object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesGasPaymentWithDefaults() *ResponsesGasPayment {
	this := ResponsesGasPayment{}
	return &this
}

// GetAmount returns the Amount field value if set, zero value otherwise.
func (o *ResponsesGasPayment) GetAmount() string {
	if o == nil || IsNil(o.Amount) {
		var ret string
		return ret
	}
	return *o.Amount
}

// GetAmountOk returns a tuple with the Amount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesGasPayment) GetAmountOk() (*string, bool) {
	if o == nil || IsNil(o.Amount) {
		return nil, false
	}
	return o.Amount, true
}

// HasAmount returns a boolean if a field has been set.
func (o *ResponsesGasPayment) HasAmount() bool {
	if o != nil && !IsNil(o.Amount) {
		return true
	}

	return false
}

// SetAmount gets a reference to the given string and assigns it to the Amount field.
func (o *ResponsesGasPayment) SetAmount(v string) {
	o.Amount = &v
}

// GetGasAmount returns the GasAmount field value if set, zero value otherwise.
func (o *ResponsesGasPayment) GetGasAmount() string {
	if o == nil || IsNil(o.GasAmount) {
		var ret string
		return ret
	}
	return *o.GasAmount
}

// GetGasAmountOk returns a tuple with the GasAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesGasPayment) GetGasAmountOk() (*string, bool) {
	if o == nil || IsNil(o.GasAmount) {
		return nil, false
	}
	return o.GasAmount, true
}

// HasGasAmount returns a boolean if a field has been set.
func (o *ResponsesGasPayment) HasGasAmount() bool {
	if o != nil && !IsNil(o.GasAmount) {
		return true
	}

	return false
}

// SetGasAmount gets a reference to the given string and assigns it to the GasAmount field.
func (o *ResponsesGasPayment) SetGasAmount(v string) {
	o.GasAmount = &v
}

// GetIgpId returns the IgpId field value if set, zero value otherwise.
func (o *ResponsesGasPayment) GetIgpId() *os.File {
	if o == nil || IsNil(o.IgpId) {
		var ret *os.File
		return ret
	}
	return *o.IgpId
}

// GetIgpIdOk returns a tuple with the IgpId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesGasPayment) GetIgpIdOk() (**os.File, bool) {
	if o == nil || IsNil(o.IgpId) {
		return nil, false
	}
	return o.IgpId, true
}

// HasIgpId returns a boolean if a field has been set.
func (o *ResponsesGasPayment) HasIgpId() bool {
	if o != nil && !IsNil(o.IgpId) {
		return true
	}

	return false
}

// SetIgpId gets a reference to the given *os.File and assigns it to the IgpId field.
func (o *ResponsesGasPayment) SetIgpId(v *os.File) {
	o.IgpId = &v
}

func (o ResponsesGasPayment) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesGasPayment) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Amount) {
		toSerialize["amount"] = o.Amount
	}
	if !IsNil(o.GasAmount) {
		toSerialize["gas_amount"] = o.GasAmount
	}
	if !IsNil(o.IgpId) {
		toSerialize["igp_id"] = o.IgpId
	}
	return toSerialize, nil
}

type NullableResponsesGasPayment struct {
	value *ResponsesGasPayment
	isSet bool
}

func (v NullableResponsesGasPayment) Get() *ResponsesGasPayment {
	return v.value
}

func (v *NullableResponsesGasPayment) Set(val *ResponsesGasPayment) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesGasPayment) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesGasPayment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesGasPayment(val *ResponsesGasPayment) *NullableResponsesGasPayment {
	return &NullableResponsesGasPayment{value: val, isSet: true}
}

func (v NullableResponsesGasPayment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesGasPayment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


