/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
)

// checks if the ResponsesTopNMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesTopNMetrics{}

// ResponsesTopNMetrics struct for ResponsesTopNMetrics
type ResponsesTopNMetrics struct {
	BlockMissedMetric *string `json:"block_missed_metric,omitempty"`
	CommissionMetric *string `json:"commission_metric,omitempty"`
	OperationTimeMetric *string `json:"operation_time_metric,omitempty"`
	SelfDelegationMetric *string `json:"self_delegation_metric,omitempty"`
	VotesMetric *string `json:"votes_metric,omitempty"`
}

// NewResponsesTopNMetrics instantiates a new ResponsesTopNMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesTopNMetrics() *ResponsesTopNMetrics {
	this := ResponsesTopNMetrics{}
	return &this
}

// NewResponsesTopNMetricsWithDefaults instantiates a new ResponsesTopNMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesTopNMetricsWithDefaults() *ResponsesTopNMetrics {
	this := ResponsesTopNMetrics{}
	return &this
}

// GetBlockMissedMetric returns the BlockMissedMetric field value if set, zero value otherwise.
func (o *ResponsesTopNMetrics) GetBlockMissedMetric() string {
	if o == nil || IsNil(o.BlockMissedMetric) {
		var ret string
		return ret
	}
	return *o.BlockMissedMetric
}

// GetBlockMissedMetricOk returns a tuple with the BlockMissedMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesTopNMetrics) GetBlockMissedMetricOk() (*string, bool) {
	if o == nil || IsNil(o.BlockMissedMetric) {
		return nil, false
	}
	return o.BlockMissedMetric, true
}

// HasBlockMissedMetric returns a boolean if a field has been set.
func (o *ResponsesTopNMetrics) HasBlockMissedMetric() bool {
	if o != nil && !IsNil(o.BlockMissedMetric) {
		return true
	}

	return false
}

// SetBlockMissedMetric gets a reference to the given string and assigns it to the BlockMissedMetric field.
func (o *ResponsesTopNMetrics) SetBlockMissedMetric(v string) {
	o.BlockMissedMetric = &v
}

// GetCommissionMetric returns the CommissionMetric field value if set, zero value otherwise.
func (o *ResponsesTopNMetrics) GetCommissionMetric() string {
	if o == nil || IsNil(o.CommissionMetric) {
		var ret string
		return ret
	}
	return *o.CommissionMetric
}

// GetCommissionMetricOk returns a tuple with the CommissionMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesTopNMetrics) GetCommissionMetricOk() (*string, bool) {
	if o == nil || IsNil(o.CommissionMetric) {
		return nil, false
	}
	return o.CommissionMetric, true
}

// HasCommissionMetric returns a boolean if a field has been set.
func (o *ResponsesTopNMetrics) HasCommissionMetric() bool {
	if o != nil && !IsNil(o.CommissionMetric) {
		return true
	}

	return false
}

// SetCommissionMetric gets a reference to the given string and assigns it to the CommissionMetric field.
func (o *ResponsesTopNMetrics) SetCommissionMetric(v string) {
	o.CommissionMetric = &v
}

// GetOperationTimeMetric returns the OperationTimeMetric field value if set, zero value otherwise.
func (o *ResponsesTopNMetrics) GetOperationTimeMetric() string {
	if o == nil || IsNil(o.OperationTimeMetric) {
		var ret string
		return ret
	}
	return *o.OperationTimeMetric
}

// GetOperationTimeMetricOk returns a tuple with the OperationTimeMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesTopNMetrics) GetOperationTimeMetricOk() (*string, bool) {
	if o == nil || IsNil(o.OperationTimeMetric) {
		return nil, false
	}
	return o.OperationTimeMetric, true
}

// HasOperationTimeMetric returns a boolean if a field has been set.
func (o *ResponsesTopNMetrics) HasOperationTimeMetric() bool {
	if o != nil && !IsNil(o.OperationTimeMetric) {
		return true
	}

	return false
}

// SetOperationTimeMetric gets a reference to the given string and assigns it to the OperationTimeMetric field.
func (o *ResponsesTopNMetrics) SetOperationTimeMetric(v string) {
	o.OperationTimeMetric = &v
}

// GetSelfDelegationMetric returns the SelfDelegationMetric field value if set, zero value otherwise.
func (o *ResponsesTopNMetrics) GetSelfDelegationMetric() string {
	if o == nil || IsNil(o.SelfDelegationMetric) {
		var ret string
		return ret
	}
	return *o.SelfDelegationMetric
}

// GetSelfDelegationMetricOk returns a tuple with the SelfDelegationMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesTopNMetrics) GetSelfDelegationMetricOk() (*string, bool) {
	if o == nil || IsNil(o.SelfDelegationMetric) {
		return nil, false
	}
	return o.SelfDelegationMetric, true
}

// HasSelfDelegationMetric returns a boolean if a field has been set.
func (o *ResponsesTopNMetrics) HasSelfDelegationMetric() bool {
	if o != nil && !IsNil(o.SelfDelegationMetric) {
		return true
	}

	return false
}

// SetSelfDelegationMetric gets a reference to the given string and assigns it to the SelfDelegationMetric field.
func (o *ResponsesTopNMetrics) SetSelfDelegationMetric(v string) {
	o.SelfDelegationMetric = &v
}

// GetVotesMetric returns the VotesMetric field value if set, zero value otherwise.
func (o *ResponsesTopNMetrics) GetVotesMetric() string {
	if o == nil || IsNil(o.VotesMetric) {
		var ret string
		return ret
	}
	return *o.VotesMetric
}

// GetVotesMetricOk returns a tuple with the VotesMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesTopNMetrics) GetVotesMetricOk() (*string, bool) {
	if o == nil || IsNil(o.VotesMetric) {
		return nil, false
	}
	return o.VotesMetric, true
}

// HasVotesMetric returns a boolean if a field has been set.
func (o *ResponsesTopNMetrics) HasVotesMetric() bool {
	if o != nil && !IsNil(o.VotesMetric) {
		return true
	}

	return false
}

// SetVotesMetric gets a reference to the given string and assigns it to the VotesMetric field.
func (o *ResponsesTopNMetrics) SetVotesMetric(v string) {
	o.VotesMetric = &v
}

func (o ResponsesTopNMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesTopNMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.BlockMissedMetric) {
		toSerialize["block_missed_metric"] = o.BlockMissedMetric
	}
	if !IsNil(o.CommissionMetric) {
		toSerialize["commission_metric"] = o.CommissionMetric
	}
	if !IsNil(o.OperationTimeMetric) {
		toSerialize["operation_time_metric"] = o.OperationTimeMetric
	}
	if !IsNil(o.SelfDelegationMetric) {
		toSerialize["self_delegation_metric"] = o.SelfDelegationMetric
	}
	if !IsNil(o.VotesMetric) {
		toSerialize["votes_metric"] = o.VotesMetric
	}
	return toSerialize, nil
}

type NullableResponsesTopNMetrics struct {
	value *ResponsesTopNMetrics
	isSet bool
}

func (v NullableResponsesTopNMetrics) Get() *ResponsesTopNMetrics {
	return v.value
}

func (v *NullableResponsesTopNMetrics) Set(val *ResponsesTopNMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesTopNMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesTopNMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesTopNMetrics(val *ResponsesTopNMetrics) *NullableResponsesTopNMetrics {
	return &NullableResponsesTopNMetrics{value: val, isSet: true}
}

func (v NullableResponsesTopNMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesTopNMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


