/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"time"
)

// checks if the ResponsesMetrics type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesMetrics{}

// ResponsesMetrics struct for ResponsesMetrics
type ResponsesMetrics struct {
	AppliedProposalsCount *int32 `json:"applied_proposals_count,omitempty"`
	BlockMissedCount *int32 `json:"block_missed_count,omitempty"`
	BlockMissedMetric *string `json:"block_missed_metric,omitempty"`
	CommissionMetric *string `json:"commission_metric,omitempty"`
	CreationTime *time.Time `json:"creation_time,omitempty"`
	Id *int32 `json:"id,omitempty"`
	MaxChangeRate *string `json:"max_change_rate,omitempty"`
	MaxRate *string `json:"max_rate,omitempty"`
	Moniker *string `json:"moniker,omitempty"`
	OperationTimeMetric *string `json:"operation_time_metric,omitempty"`
	SelfDelegationAmount *string `json:"self_delegation_amount,omitempty"`
	SelfDelegationMetric *string `json:"self_delegation_metric,omitempty"`
	Stake *string `json:"stake,omitempty"`
	VotesCount *int32 `json:"votes_count,omitempty"`
	VotesMetric *string `json:"votes_metric,omitempty"`
}

// NewResponsesMetrics instantiates a new ResponsesMetrics object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesMetrics() *ResponsesMetrics {
	this := ResponsesMetrics{}
	return &this
}

// NewResponsesMetricsWithDefaults instantiates a new ResponsesMetrics object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesMetricsWithDefaults() *ResponsesMetrics {
	this := ResponsesMetrics{}
	return &this
}

// GetAppliedProposalsCount returns the AppliedProposalsCount field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetAppliedProposalsCount() int32 {
	if o == nil || IsNil(o.AppliedProposalsCount) {
		var ret int32
		return ret
	}
	return *o.AppliedProposalsCount
}

// GetAppliedProposalsCountOk returns a tuple with the AppliedProposalsCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetAppliedProposalsCountOk() (*int32, bool) {
	if o == nil || IsNil(o.AppliedProposalsCount) {
		return nil, false
	}
	return o.AppliedProposalsCount, true
}

// HasAppliedProposalsCount returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasAppliedProposalsCount() bool {
	if o != nil && !IsNil(o.AppliedProposalsCount) {
		return true
	}

	return false
}

// SetAppliedProposalsCount gets a reference to the given int32 and assigns it to the AppliedProposalsCount field.
func (o *ResponsesMetrics) SetAppliedProposalsCount(v int32) {
	o.AppliedProposalsCount = &v
}

// GetBlockMissedCount returns the BlockMissedCount field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetBlockMissedCount() int32 {
	if o == nil || IsNil(o.BlockMissedCount) {
		var ret int32
		return ret
	}
	return *o.BlockMissedCount
}

// GetBlockMissedCountOk returns a tuple with the BlockMissedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetBlockMissedCountOk() (*int32, bool) {
	if o == nil || IsNil(o.BlockMissedCount) {
		return nil, false
	}
	return o.BlockMissedCount, true
}

// HasBlockMissedCount returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasBlockMissedCount() bool {
	if o != nil && !IsNil(o.BlockMissedCount) {
		return true
	}

	return false
}

// SetBlockMissedCount gets a reference to the given int32 and assigns it to the BlockMissedCount field.
func (o *ResponsesMetrics) SetBlockMissedCount(v int32) {
	o.BlockMissedCount = &v
}

// GetBlockMissedMetric returns the BlockMissedMetric field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetBlockMissedMetric() string {
	if o == nil || IsNil(o.BlockMissedMetric) {
		var ret string
		return ret
	}
	return *o.BlockMissedMetric
}

// GetBlockMissedMetricOk returns a tuple with the BlockMissedMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetBlockMissedMetricOk() (*string, bool) {
	if o == nil || IsNil(o.BlockMissedMetric) {
		return nil, false
	}
	return o.BlockMissedMetric, true
}

// HasBlockMissedMetric returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasBlockMissedMetric() bool {
	if o != nil && !IsNil(o.BlockMissedMetric) {
		return true
	}

	return false
}

// SetBlockMissedMetric gets a reference to the given string and assigns it to the BlockMissedMetric field.
func (o *ResponsesMetrics) SetBlockMissedMetric(v string) {
	o.BlockMissedMetric = &v
}

// GetCommissionMetric returns the CommissionMetric field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetCommissionMetric() string {
	if o == nil || IsNil(o.CommissionMetric) {
		var ret string
		return ret
	}
	return *o.CommissionMetric
}

// GetCommissionMetricOk returns a tuple with the CommissionMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetCommissionMetricOk() (*string, bool) {
	if o == nil || IsNil(o.CommissionMetric) {
		return nil, false
	}
	return o.CommissionMetric, true
}

// HasCommissionMetric returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasCommissionMetric() bool {
	if o != nil && !IsNil(o.CommissionMetric) {
		return true
	}

	return false
}

// SetCommissionMetric gets a reference to the given string and assigns it to the CommissionMetric field.
func (o *ResponsesMetrics) SetCommissionMetric(v string) {
	o.CommissionMetric = &v
}

// GetCreationTime returns the CreationTime field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetCreationTime() time.Time {
	if o == nil || IsNil(o.CreationTime) {
		var ret time.Time
		return ret
	}
	return *o.CreationTime
}

// GetCreationTimeOk returns a tuple with the CreationTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetCreationTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreationTime) {
		return nil, false
	}
	return o.CreationTime, true
}

// HasCreationTime returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasCreationTime() bool {
	if o != nil && !IsNil(o.CreationTime) {
		return true
	}

	return false
}

// SetCreationTime gets a reference to the given time.Time and assigns it to the CreationTime field.
func (o *ResponsesMetrics) SetCreationTime(v time.Time) {
	o.CreationTime = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetId() int32 {
	if o == nil || IsNil(o.Id) {
		var ret int32
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetIdOk() (*int32, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int32 and assigns it to the Id field.
func (o *ResponsesMetrics) SetId(v int32) {
	o.Id = &v
}

// GetMaxChangeRate returns the MaxChangeRate field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetMaxChangeRate() string {
	if o == nil || IsNil(o.MaxChangeRate) {
		var ret string
		return ret
	}
	return *o.MaxChangeRate
}

// GetMaxChangeRateOk returns a tuple with the MaxChangeRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetMaxChangeRateOk() (*string, bool) {
	if o == nil || IsNil(o.MaxChangeRate) {
		return nil, false
	}
	return o.MaxChangeRate, true
}

// HasMaxChangeRate returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasMaxChangeRate() bool {
	if o != nil && !IsNil(o.MaxChangeRate) {
		return true
	}

	return false
}

// SetMaxChangeRate gets a reference to the given string and assigns it to the MaxChangeRate field.
func (o *ResponsesMetrics) SetMaxChangeRate(v string) {
	o.MaxChangeRate = &v
}

// GetMaxRate returns the MaxRate field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetMaxRate() string {
	if o == nil || IsNil(o.MaxRate) {
		var ret string
		return ret
	}
	return *o.MaxRate
}

// GetMaxRateOk returns a tuple with the MaxRate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetMaxRateOk() (*string, bool) {
	if o == nil || IsNil(o.MaxRate) {
		return nil, false
	}
	return o.MaxRate, true
}

// HasMaxRate returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasMaxRate() bool {
	if o != nil && !IsNil(o.MaxRate) {
		return true
	}

	return false
}

// SetMaxRate gets a reference to the given string and assigns it to the MaxRate field.
func (o *ResponsesMetrics) SetMaxRate(v string) {
	o.MaxRate = &v
}

// GetMoniker returns the Moniker field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetMoniker() string {
	if o == nil || IsNil(o.Moniker) {
		var ret string
		return ret
	}
	return *o.Moniker
}

// GetMonikerOk returns a tuple with the Moniker field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetMonikerOk() (*string, bool) {
	if o == nil || IsNil(o.Moniker) {
		return nil, false
	}
	return o.Moniker, true
}

// HasMoniker returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasMoniker() bool {
	if o != nil && !IsNil(o.Moniker) {
		return true
	}

	return false
}

// SetMoniker gets a reference to the given string and assigns it to the Moniker field.
func (o *ResponsesMetrics) SetMoniker(v string) {
	o.Moniker = &v
}

// GetOperationTimeMetric returns the OperationTimeMetric field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetOperationTimeMetric() string {
	if o == nil || IsNil(o.OperationTimeMetric) {
		var ret string
		return ret
	}
	return *o.OperationTimeMetric
}

// GetOperationTimeMetricOk returns a tuple with the OperationTimeMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetOperationTimeMetricOk() (*string, bool) {
	if o == nil || IsNil(o.OperationTimeMetric) {
		return nil, false
	}
	return o.OperationTimeMetric, true
}

// HasOperationTimeMetric returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasOperationTimeMetric() bool {
	if o != nil && !IsNil(o.OperationTimeMetric) {
		return true
	}

	return false
}

// SetOperationTimeMetric gets a reference to the given string and assigns it to the OperationTimeMetric field.
func (o *ResponsesMetrics) SetOperationTimeMetric(v string) {
	o.OperationTimeMetric = &v
}

// GetSelfDelegationAmount returns the SelfDelegationAmount field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetSelfDelegationAmount() string {
	if o == nil || IsNil(o.SelfDelegationAmount) {
		var ret string
		return ret
	}
	return *o.SelfDelegationAmount
}

// GetSelfDelegationAmountOk returns a tuple with the SelfDelegationAmount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetSelfDelegationAmountOk() (*string, bool) {
	if o == nil || IsNil(o.SelfDelegationAmount) {
		return nil, false
	}
	return o.SelfDelegationAmount, true
}

// HasSelfDelegationAmount returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasSelfDelegationAmount() bool {
	if o != nil && !IsNil(o.SelfDelegationAmount) {
		return true
	}

	return false
}

// SetSelfDelegationAmount gets a reference to the given string and assigns it to the SelfDelegationAmount field.
func (o *ResponsesMetrics) SetSelfDelegationAmount(v string) {
	o.SelfDelegationAmount = &v
}

// GetSelfDelegationMetric returns the SelfDelegationMetric field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetSelfDelegationMetric() string {
	if o == nil || IsNil(o.SelfDelegationMetric) {
		var ret string
		return ret
	}
	return *o.SelfDelegationMetric
}

// GetSelfDelegationMetricOk returns a tuple with the SelfDelegationMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetSelfDelegationMetricOk() (*string, bool) {
	if o == nil || IsNil(o.SelfDelegationMetric) {
		return nil, false
	}
	return o.SelfDelegationMetric, true
}

// HasSelfDelegationMetric returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasSelfDelegationMetric() bool {
	if o != nil && !IsNil(o.SelfDelegationMetric) {
		return true
	}

	return false
}

// SetSelfDelegationMetric gets a reference to the given string and assigns it to the SelfDelegationMetric field.
func (o *ResponsesMetrics) SetSelfDelegationMetric(v string) {
	o.SelfDelegationMetric = &v
}

// GetStake returns the Stake field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetStake() string {
	if o == nil || IsNil(o.Stake) {
		var ret string
		return ret
	}
	return *o.Stake
}

// GetStakeOk returns a tuple with the Stake field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetStakeOk() (*string, bool) {
	if o == nil || IsNil(o.Stake) {
		return nil, false
	}
	return o.Stake, true
}

// HasStake returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasStake() bool {
	if o != nil && !IsNil(o.Stake) {
		return true
	}

	return false
}

// SetStake gets a reference to the given string and assigns it to the Stake field.
func (o *ResponsesMetrics) SetStake(v string) {
	o.Stake = &v
}

// GetVotesCount returns the VotesCount field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetVotesCount() int32 {
	if o == nil || IsNil(o.VotesCount) {
		var ret int32
		return ret
	}
	return *o.VotesCount
}

// GetVotesCountOk returns a tuple with the VotesCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetVotesCountOk() (*int32, bool) {
	if o == nil || IsNil(o.VotesCount) {
		return nil, false
	}
	return o.VotesCount, true
}

// HasVotesCount returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasVotesCount() bool {
	if o != nil && !IsNil(o.VotesCount) {
		return true
	}

	return false
}

// SetVotesCount gets a reference to the given int32 and assigns it to the VotesCount field.
func (o *ResponsesMetrics) SetVotesCount(v int32) {
	o.VotesCount = &v
}

// GetVotesMetric returns the VotesMetric field value if set, zero value otherwise.
func (o *ResponsesMetrics) GetVotesMetric() string {
	if o == nil || IsNil(o.VotesMetric) {
		var ret string
		return ret
	}
	return *o.VotesMetric
}

// GetVotesMetricOk returns a tuple with the VotesMetric field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesMetrics) GetVotesMetricOk() (*string, bool) {
	if o == nil || IsNil(o.VotesMetric) {
		return nil, false
	}
	return o.VotesMetric, true
}

// HasVotesMetric returns a boolean if a field has been set.
func (o *ResponsesMetrics) HasVotesMetric() bool {
	if o != nil && !IsNil(o.VotesMetric) {
		return true
	}

	return false
}

// SetVotesMetric gets a reference to the given string and assigns it to the VotesMetric field.
func (o *ResponsesMetrics) SetVotesMetric(v string) {
	o.VotesMetric = &v
}

func (o ResponsesMetrics) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesMetrics) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AppliedProposalsCount) {
		toSerialize["applied_proposals_count"] = o.AppliedProposalsCount
	}
	if !IsNil(o.BlockMissedCount) {
		toSerialize["block_missed_count"] = o.BlockMissedCount
	}
	if !IsNil(o.BlockMissedMetric) {
		toSerialize["block_missed_metric"] = o.BlockMissedMetric
	}
	if !IsNil(o.CommissionMetric) {
		toSerialize["commission_metric"] = o.CommissionMetric
	}
	if !IsNil(o.CreationTime) {
		toSerialize["creation_time"] = o.CreationTime
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MaxChangeRate) {
		toSerialize["max_change_rate"] = o.MaxChangeRate
	}
	if !IsNil(o.MaxRate) {
		toSerialize["max_rate"] = o.MaxRate
	}
	if !IsNil(o.Moniker) {
		toSerialize["moniker"] = o.Moniker
	}
	if !IsNil(o.OperationTimeMetric) {
		toSerialize["operation_time_metric"] = o.OperationTimeMetric
	}
	if !IsNil(o.SelfDelegationAmount) {
		toSerialize["self_delegation_amount"] = o.SelfDelegationAmount
	}
	if !IsNil(o.SelfDelegationMetric) {
		toSerialize["self_delegation_metric"] = o.SelfDelegationMetric
	}
	if !IsNil(o.Stake) {
		toSerialize["stake"] = o.Stake
	}
	if !IsNil(o.VotesCount) {
		toSerialize["votes_count"] = o.VotesCount
	}
	if !IsNil(o.VotesMetric) {
		toSerialize["votes_metric"] = o.VotesMetric
	}
	return toSerialize, nil
}

type NullableResponsesMetrics struct {
	value *ResponsesMetrics
	isSet bool
}

func (v NullableResponsesMetrics) Get() *ResponsesMetrics {
	return v.value
}

func (v *NullableResponsesMetrics) Set(val *ResponsesMetrics) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesMetrics) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesMetrics) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesMetrics(val *ResponsesMetrics) *NullableResponsesMetrics {
	return &NullableResponsesMetrics{value: val, isSet: true}
}

func (v NullableResponsesMetrics) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesMetrics) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


