/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"time"
)

// checks if the ResponsesStakingDistributionItem type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesStakingDistributionItem{}

// ResponsesStakingDistributionItem struct for ResponsesStakingDistributionItem
type ResponsesStakingDistributionItem struct {
	Percent *string `json:"percent,omitempty"`
	Time *time.Time `json:"time,omitempty"`
	Value *string `json:"value,omitempty"`
}

// NewResponsesStakingDistributionItem instantiates a new ResponsesStakingDistributionItem object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesStakingDistributionItem() *ResponsesStakingDistributionItem {
	this := ResponsesStakingDistributionItem{}
	return &this
}

// NewResponsesStakingDistributionItemWithDefaults instantiates a new ResponsesStakingDistributionItem object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesStakingDistributionItemWithDefaults() *ResponsesStakingDistributionItem {
	this := ResponsesStakingDistributionItem{}
	return &this
}

// GetPercent returns the Percent field value if set, zero value otherwise.
func (o *ResponsesStakingDistributionItem) GetPercent() string {
	if o == nil || IsNil(o.Percent) {
		var ret string
		return ret
	}
	return *o.Percent
}

// GetPercentOk returns a tuple with the Percent field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesStakingDistributionItem) GetPercentOk() (*string, bool) {
	if o == nil || IsNil(o.Percent) {
		return nil, false
	}
	return o.Percent, true
}

// HasPercent returns a boolean if a field has been set.
func (o *ResponsesStakingDistributionItem) HasPercent() bool {
	if o != nil && !IsNil(o.Percent) {
		return true
	}

	return false
}

// SetPercent gets a reference to the given string and assigns it to the Percent field.
func (o *ResponsesStakingDistributionItem) SetPercent(v string) {
	o.Percent = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ResponsesStakingDistributionItem) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesStakingDistributionItem) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ResponsesStakingDistributionItem) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *ResponsesStakingDistributionItem) SetTime(v time.Time) {
	o.Time = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *ResponsesStakingDistributionItem) GetValue() string {
	if o == nil || IsNil(o.Value) {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesStakingDistributionItem) GetValueOk() (*string, bool) {
	if o == nil || IsNil(o.Value) {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *ResponsesStakingDistributionItem) HasValue() bool {
	if o != nil && !IsNil(o.Value) {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *ResponsesStakingDistributionItem) SetValue(v string) {
	o.Value = &v
}

func (o ResponsesStakingDistributionItem) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesStakingDistributionItem) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Percent) {
		toSerialize["percent"] = o.Percent
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Value) {
		toSerialize["value"] = o.Value
	}
	return toSerialize, nil
}

type NullableResponsesStakingDistributionItem struct {
	value *ResponsesStakingDistributionItem
	isSet bool
}

func (v NullableResponsesStakingDistributionItem) Get() *ResponsesStakingDistributionItem {
	return v.value
}

func (v *NullableResponsesStakingDistributionItem) Set(val *ResponsesStakingDistributionItem) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesStakingDistributionItem) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesStakingDistributionItem) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesStakingDistributionItem(val *ResponsesStakingDistributionItem) *NullableResponsesStakingDistributionItem {
	return &NullableResponsesStakingDistributionItem{value: val, isSet: true}
}

func (v NullableResponsesStakingDistributionItem) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesStakingDistributionItem) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


