/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
)

// checks if the ResponsesFibre type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesFibre{}

// ResponsesFibre struct for ResponsesFibre
type ResponsesFibre struct {
	Height *int64 `json:"height,omitempty"`
	Host *string `json:"host,omitempty"`
}

// NewResponsesFibre instantiates a new ResponsesFibre object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesFibre() *ResponsesFibre {
	this := ResponsesFibre{}
	return &this
}

// NewResponsesFibreWithDefaults instantiates a new ResponsesFibre object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesFibreWithDefaults() *ResponsesFibre {
	this := ResponsesFibre{}
	return &this
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ResponsesFibre) GetHeight() int64 {
	if o == nil || IsNil(o.Height) {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesFibre) GetHeightOk() (*int64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ResponsesFibre) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *ResponsesFibre) SetHeight(v int64) {
	o.Height = &v
}

// GetHost returns the Host field value if set, zero value otherwise.
func (o *ResponsesFibre) GetHost() string {
	if o == nil || IsNil(o.Host) {
		var ret string
		return ret
	}
	return *o.Host
}

// GetHostOk returns a tuple with the Host field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesFibre) GetHostOk() (*string, bool) {
	if o == nil || IsNil(o.Host) {
		return nil, false
	}
	return o.Host, true
}

// HasHost returns a boolean if a field has been set.
func (o *ResponsesFibre) HasHost() bool {
	if o != nil && !IsNil(o.Host) {
		return true
	}

	return false
}

// SetHost gets a reference to the given string and assigns it to the Host field.
func (o *ResponsesFibre) SetHost(v string) {
	o.Host = &v
}

func (o ResponsesFibre) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesFibre) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Host) {
		toSerialize["host"] = o.Host
	}
	return toSerialize, nil
}

type NullableResponsesFibre struct {
	value *ResponsesFibre
	isSet bool
}

func (v NullableResponsesFibre) Get() *ResponsesFibre {
	return v.value
}

func (v *NullableResponsesFibre) Set(val *ResponsesFibre) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesFibre) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesFibre) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesFibre(val *ResponsesFibre) *NullableResponsesFibre {
	return &NullableResponsesFibre{value: val, isSet: true}
}

func (v NullableResponsesFibre) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesFibre) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


