/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"os"
	"time"
)

// checks if the ResponsesForwarding type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesForwarding{}

// ResponsesForwarding struct for ResponsesForwarding
type ResponsesForwarding struct {
	Chain *ResponsesChainMetadata `json:"chain,omitempty"`
	DestAddress **os.File `json:"dest_address,omitempty"`
	DestDomain *int64 `json:"dest_domain,omitempty"`
	FailedCount *int64 `json:"failed_count,omitempty"`
	ForwardAddress *ResponsesShortAddress `json:"forward_address,omitempty"`
	Height *int64 `json:"height,omitempty"`
	Id *int64 `json:"id,omitempty"`
	Inputs []ResponsesForwardingInput `json:"inputs,omitempty"`
	SuccessCount *int64 `json:"success_count,omitempty"`
	Time *time.Time `json:"time,omitempty"`
	Transfers []int32 `json:"transfers,omitempty"`
	TxHash **os.File `json:"tx_hash,omitempty"`
}

// NewResponsesForwarding instantiates a new ResponsesForwarding object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesForwarding() *ResponsesForwarding {
	this := ResponsesForwarding{}
	return &this
}

// NewResponsesForwardingWithDefaults instantiates a new ResponsesForwarding object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesForwardingWithDefaults() *ResponsesForwarding {
	this := ResponsesForwarding{}
	return &this
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetChain() ResponsesChainMetadata {
	if o == nil || IsNil(o.Chain) {
		var ret ResponsesChainMetadata
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetChainOk() (*ResponsesChainMetadata, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given ResponsesChainMetadata and assigns it to the Chain field.
func (o *ResponsesForwarding) SetChain(v ResponsesChainMetadata) {
	o.Chain = &v
}

// GetDestAddress returns the DestAddress field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetDestAddress() *os.File {
	if o == nil || IsNil(o.DestAddress) {
		var ret *os.File
		return ret
	}
	return *o.DestAddress
}

// GetDestAddressOk returns a tuple with the DestAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetDestAddressOk() (**os.File, bool) {
	if o == nil || IsNil(o.DestAddress) {
		return nil, false
	}
	return o.DestAddress, true
}

// HasDestAddress returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasDestAddress() bool {
	if o != nil && !IsNil(o.DestAddress) {
		return true
	}

	return false
}

// SetDestAddress gets a reference to the given *os.File and assigns it to the DestAddress field.
func (o *ResponsesForwarding) SetDestAddress(v *os.File) {
	o.DestAddress = &v
}

// GetDestDomain returns the DestDomain field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetDestDomain() int64 {
	if o == nil || IsNil(o.DestDomain) {
		var ret int64
		return ret
	}
	return *o.DestDomain
}

// GetDestDomainOk returns a tuple with the DestDomain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetDestDomainOk() (*int64, bool) {
	if o == nil || IsNil(o.DestDomain) {
		return nil, false
	}
	return o.DestDomain, true
}

// HasDestDomain returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasDestDomain() bool {
	if o != nil && !IsNil(o.DestDomain) {
		return true
	}

	return false
}

// SetDestDomain gets a reference to the given int64 and assigns it to the DestDomain field.
func (o *ResponsesForwarding) SetDestDomain(v int64) {
	o.DestDomain = &v
}

// GetFailedCount returns the FailedCount field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetFailedCount() int64 {
	if o == nil || IsNil(o.FailedCount) {
		var ret int64
		return ret
	}
	return *o.FailedCount
}

// GetFailedCountOk returns a tuple with the FailedCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetFailedCountOk() (*int64, bool) {
	if o == nil || IsNil(o.FailedCount) {
		return nil, false
	}
	return o.FailedCount, true
}

// HasFailedCount returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasFailedCount() bool {
	if o != nil && !IsNil(o.FailedCount) {
		return true
	}

	return false
}

// SetFailedCount gets a reference to the given int64 and assigns it to the FailedCount field.
func (o *ResponsesForwarding) SetFailedCount(v int64) {
	o.FailedCount = &v
}

// GetForwardAddress returns the ForwardAddress field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetForwardAddress() ResponsesShortAddress {
	if o == nil || IsNil(o.ForwardAddress) {
		var ret ResponsesShortAddress
		return ret
	}
	return *o.ForwardAddress
}

// GetForwardAddressOk returns a tuple with the ForwardAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetForwardAddressOk() (*ResponsesShortAddress, bool) {
	if o == nil || IsNil(o.ForwardAddress) {
		return nil, false
	}
	return o.ForwardAddress, true
}

// HasForwardAddress returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasForwardAddress() bool {
	if o != nil && !IsNil(o.ForwardAddress) {
		return true
	}

	return false
}

// SetForwardAddress gets a reference to the given ResponsesShortAddress and assigns it to the ForwardAddress field.
func (o *ResponsesForwarding) SetForwardAddress(v ResponsesShortAddress) {
	o.ForwardAddress = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetHeight() int64 {
	if o == nil || IsNil(o.Height) {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetHeightOk() (*int64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *ResponsesForwarding) SetHeight(v int64) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ResponsesForwarding) SetId(v int64) {
	o.Id = &v
}

// GetInputs returns the Inputs field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetInputs() []ResponsesForwardingInput {
	if o == nil || IsNil(o.Inputs) {
		var ret []ResponsesForwardingInput
		return ret
	}
	return o.Inputs
}

// GetInputsOk returns a tuple with the Inputs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetInputsOk() ([]ResponsesForwardingInput, bool) {
	if o == nil || IsNil(o.Inputs) {
		return nil, false
	}
	return o.Inputs, true
}

// HasInputs returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasInputs() bool {
	if o != nil && !IsNil(o.Inputs) {
		return true
	}

	return false
}

// SetInputs gets a reference to the given []ResponsesForwardingInput and assigns it to the Inputs field.
func (o *ResponsesForwarding) SetInputs(v []ResponsesForwardingInput) {
	o.Inputs = v
}

// GetSuccessCount returns the SuccessCount field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetSuccessCount() int64 {
	if o == nil || IsNil(o.SuccessCount) {
		var ret int64
		return ret
	}
	return *o.SuccessCount
}

// GetSuccessCountOk returns a tuple with the SuccessCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetSuccessCountOk() (*int64, bool) {
	if o == nil || IsNil(o.SuccessCount) {
		return nil, false
	}
	return o.SuccessCount, true
}

// HasSuccessCount returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasSuccessCount() bool {
	if o != nil && !IsNil(o.SuccessCount) {
		return true
	}

	return false
}

// SetSuccessCount gets a reference to the given int64 and assigns it to the SuccessCount field.
func (o *ResponsesForwarding) SetSuccessCount(v int64) {
	o.SuccessCount = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *ResponsesForwarding) SetTime(v time.Time) {
	o.Time = &v
}

// GetTransfers returns the Transfers field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetTransfers() []int32 {
	if o == nil || IsNil(o.Transfers) {
		var ret []int32
		return ret
	}
	return o.Transfers
}

// GetTransfersOk returns a tuple with the Transfers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetTransfersOk() ([]int32, bool) {
	if o == nil || IsNil(o.Transfers) {
		return nil, false
	}
	return o.Transfers, true
}

// HasTransfers returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasTransfers() bool {
	if o != nil && !IsNil(o.Transfers) {
		return true
	}

	return false
}

// SetTransfers gets a reference to the given []int32 and assigns it to the Transfers field.
func (o *ResponsesForwarding) SetTransfers(v []int32) {
	o.Transfers = v
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *ResponsesForwarding) GetTxHash() *os.File {
	if o == nil || IsNil(o.TxHash) {
		var ret *os.File
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwarding) GetTxHashOk() (**os.File, bool) {
	if o == nil || IsNil(o.TxHash) {
		return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *ResponsesForwarding) HasTxHash() bool {
	if o != nil && !IsNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given *os.File and assigns it to the TxHash field.
func (o *ResponsesForwarding) SetTxHash(v *os.File) {
	o.TxHash = &v
}

func (o ResponsesForwarding) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesForwarding) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.DestAddress) {
		toSerialize["dest_address"] = o.DestAddress
	}
	if !IsNil(o.DestDomain) {
		toSerialize["dest_domain"] = o.DestDomain
	}
	if !IsNil(o.FailedCount) {
		toSerialize["failed_count"] = o.FailedCount
	}
	if !IsNil(o.ForwardAddress) {
		toSerialize["forward_address"] = o.ForwardAddress
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.Inputs) {
		toSerialize["inputs"] = o.Inputs
	}
	if !IsNil(o.SuccessCount) {
		toSerialize["success_count"] = o.SuccessCount
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.Transfers) {
		toSerialize["transfers"] = o.Transfers
	}
	if !IsNil(o.TxHash) {
		toSerialize["tx_hash"] = o.TxHash
	}
	return toSerialize, nil
}

type NullableResponsesForwarding struct {
	value *ResponsesForwarding
	isSet bool
}

func (v NullableResponsesForwarding) Get() *ResponsesForwarding {
	return v.value
}

func (v *NullableResponsesForwarding) Set(val *ResponsesForwarding) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesForwarding) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesForwarding) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesForwarding(val *ResponsesForwarding) *NullableResponsesForwarding {
	return &NullableResponsesForwarding{value: val, isSet: true}
}

func (v NullableResponsesForwarding) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesForwarding) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


