/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"os"
	"time"
)

// checks if the ResponsesHyperlaneIgp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesHyperlaneIgp{}

// ResponsesHyperlaneIgp struct for ResponsesHyperlaneIgp
type ResponsesHyperlaneIgp struct {
	Configs []ResponsesHyperlaneIgpConfig `json:"configs,omitempty"`
	Denom *string `json:"denom,omitempty"`
	Height *int64 `json:"height,omitempty"`
	Id *int64 `json:"id,omitempty"`
	IgpId **os.File `json:"igp_id,omitempty"`
	Owner *ResponsesShortAddress `json:"owner,omitempty"`
	Time *time.Time `json:"time,omitempty"`
}

// NewResponsesHyperlaneIgp instantiates a new ResponsesHyperlaneIgp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesHyperlaneIgp() *ResponsesHyperlaneIgp {
	this := ResponsesHyperlaneIgp{}
	return &this
}

// NewResponsesHyperlaneIgpWithDefaults instantiates a new ResponsesHyperlaneIgp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesHyperlaneIgpWithDefaults() *ResponsesHyperlaneIgp {
	this := ResponsesHyperlaneIgp{}
	return &this
}

// GetConfigs returns the Configs field value if set, zero value otherwise.
func (o *ResponsesHyperlaneIgp) GetConfigs() []ResponsesHyperlaneIgpConfig {
	if o == nil || IsNil(o.Configs) {
		var ret []ResponsesHyperlaneIgpConfig
		return ret
	}
	return o.Configs
}

// GetConfigsOk returns a tuple with the Configs field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneIgp) GetConfigsOk() ([]ResponsesHyperlaneIgpConfig, bool) {
	if o == nil || IsNil(o.Configs) {
		return nil, false
	}
	return o.Configs, true
}

// HasConfigs returns a boolean if a field has been set.
func (o *ResponsesHyperlaneIgp) HasConfigs() bool {
	if o != nil && !IsNil(o.Configs) {
		return true
	}

	return false
}

// SetConfigs gets a reference to the given []ResponsesHyperlaneIgpConfig and assigns it to the Configs field.
func (o *ResponsesHyperlaneIgp) SetConfigs(v []ResponsesHyperlaneIgpConfig) {
	o.Configs = v
}

// GetDenom returns the Denom field value if set, zero value otherwise.
func (o *ResponsesHyperlaneIgp) GetDenom() string {
	if o == nil || IsNil(o.Denom) {
		var ret string
		return ret
	}
	return *o.Denom
}

// GetDenomOk returns a tuple with the Denom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneIgp) GetDenomOk() (*string, bool) {
	if o == nil || IsNil(o.Denom) {
		return nil, false
	}
	return o.Denom, true
}

// HasDenom returns a boolean if a field has been set.
func (o *ResponsesHyperlaneIgp) HasDenom() bool {
	if o != nil && !IsNil(o.Denom) {
		return true
	}

	return false
}

// SetDenom gets a reference to the given string and assigns it to the Denom field.
func (o *ResponsesHyperlaneIgp) SetDenom(v string) {
	o.Denom = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ResponsesHyperlaneIgp) GetHeight() int64 {
	if o == nil || IsNil(o.Height) {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneIgp) GetHeightOk() (*int64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ResponsesHyperlaneIgp) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *ResponsesHyperlaneIgp) SetHeight(v int64) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponsesHyperlaneIgp) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneIgp) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponsesHyperlaneIgp) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ResponsesHyperlaneIgp) SetId(v int64) {
	o.Id = &v
}

// GetIgpId returns the IgpId field value if set, zero value otherwise.
func (o *ResponsesHyperlaneIgp) GetIgpId() *os.File {
	if o == nil || IsNil(o.IgpId) {
		var ret *os.File
		return ret
	}
	return *o.IgpId
}

// GetIgpIdOk returns a tuple with the IgpId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneIgp) GetIgpIdOk() (**os.File, bool) {
	if o == nil || IsNil(o.IgpId) {
		return nil, false
	}
	return o.IgpId, true
}

// HasIgpId returns a boolean if a field has been set.
func (o *ResponsesHyperlaneIgp) HasIgpId() bool {
	if o != nil && !IsNil(o.IgpId) {
		return true
	}

	return false
}

// SetIgpId gets a reference to the given *os.File and assigns it to the IgpId field.
func (o *ResponsesHyperlaneIgp) SetIgpId(v *os.File) {
	o.IgpId = &v
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *ResponsesHyperlaneIgp) GetOwner() ResponsesShortAddress {
	if o == nil || IsNil(o.Owner) {
		var ret ResponsesShortAddress
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneIgp) GetOwnerOk() (*ResponsesShortAddress, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *ResponsesHyperlaneIgp) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given ResponsesShortAddress and assigns it to the Owner field.
func (o *ResponsesHyperlaneIgp) SetOwner(v ResponsesShortAddress) {
	o.Owner = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ResponsesHyperlaneIgp) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesHyperlaneIgp) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ResponsesHyperlaneIgp) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *ResponsesHyperlaneIgp) SetTime(v time.Time) {
	o.Time = &v
}

func (o ResponsesHyperlaneIgp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesHyperlaneIgp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Configs) {
		toSerialize["configs"] = o.Configs
	}
	if !IsNil(o.Denom) {
		toSerialize["denom"] = o.Denom
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.IgpId) {
		toSerialize["igp_id"] = o.IgpId
	}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	return toSerialize, nil
}

type NullableResponsesHyperlaneIgp struct {
	value *ResponsesHyperlaneIgp
	isSet bool
}

func (v NullableResponsesHyperlaneIgp) Get() *ResponsesHyperlaneIgp {
	return v.value
}

func (v *NullableResponsesHyperlaneIgp) Set(val *ResponsesHyperlaneIgp) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesHyperlaneIgp) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesHyperlaneIgp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesHyperlaneIgp(val *ResponsesHyperlaneIgp) *NullableResponsesHyperlaneIgp {
	return &NullableResponsesHyperlaneIgp{value: val, isSet: true}
}

func (v NullableResponsesHyperlaneIgp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesHyperlaneIgp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


