/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"time"
	"os"
)

// checks if the ResponsesForwardingInput type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesForwardingInput{}

// ResponsesForwardingInput struct for ResponsesForwardingInput
type ResponsesForwardingInput struct {
	Chain *ResponsesChainMetadata `json:"chain,omitempty"`
	Denom *string `json:"denom,omitempty"`
	From *string `json:"from,omitempty"`
	Height *int64 `json:"height,omitempty"`
	Received *string `json:"received,omitempty"`
	Time *time.Time `json:"time,omitempty"`
	TxHash **os.File `json:"tx_hash,omitempty"`
}

// NewResponsesForwardingInput instantiates a new ResponsesForwardingInput object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesForwardingInput() *ResponsesForwardingInput {
	this := ResponsesForwardingInput{}
	return &this
}

// NewResponsesForwardingInputWithDefaults instantiates a new ResponsesForwardingInput object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesForwardingInputWithDefaults() *ResponsesForwardingInput {
	this := ResponsesForwardingInput{}
	return &this
}

// GetChain returns the Chain field value if set, zero value otherwise.
func (o *ResponsesForwardingInput) GetChain() ResponsesChainMetadata {
	if o == nil || IsNil(o.Chain) {
		var ret ResponsesChainMetadata
		return ret
	}
	return *o.Chain
}

// GetChainOk returns a tuple with the Chain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwardingInput) GetChainOk() (*ResponsesChainMetadata, bool) {
	if o == nil || IsNil(o.Chain) {
		return nil, false
	}
	return o.Chain, true
}

// HasChain returns a boolean if a field has been set.
func (o *ResponsesForwardingInput) HasChain() bool {
	if o != nil && !IsNil(o.Chain) {
		return true
	}

	return false
}

// SetChain gets a reference to the given ResponsesChainMetadata and assigns it to the Chain field.
func (o *ResponsesForwardingInput) SetChain(v ResponsesChainMetadata) {
	o.Chain = &v
}

// GetDenom returns the Denom field value if set, zero value otherwise.
func (o *ResponsesForwardingInput) GetDenom() string {
	if o == nil || IsNil(o.Denom) {
		var ret string
		return ret
	}
	return *o.Denom
}

// GetDenomOk returns a tuple with the Denom field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwardingInput) GetDenomOk() (*string, bool) {
	if o == nil || IsNil(o.Denom) {
		return nil, false
	}
	return o.Denom, true
}

// HasDenom returns a boolean if a field has been set.
func (o *ResponsesForwardingInput) HasDenom() bool {
	if o != nil && !IsNil(o.Denom) {
		return true
	}

	return false
}

// SetDenom gets a reference to the given string and assigns it to the Denom field.
func (o *ResponsesForwardingInput) SetDenom(v string) {
	o.Denom = &v
}

// GetFrom returns the From field value if set, zero value otherwise.
func (o *ResponsesForwardingInput) GetFrom() string {
	if o == nil || IsNil(o.From) {
		var ret string
		return ret
	}
	return *o.From
}

// GetFromOk returns a tuple with the From field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwardingInput) GetFromOk() (*string, bool) {
	if o == nil || IsNil(o.From) {
		return nil, false
	}
	return o.From, true
}

// HasFrom returns a boolean if a field has been set.
func (o *ResponsesForwardingInput) HasFrom() bool {
	if o != nil && !IsNil(o.From) {
		return true
	}

	return false
}

// SetFrom gets a reference to the given string and assigns it to the From field.
func (o *ResponsesForwardingInput) SetFrom(v string) {
	o.From = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ResponsesForwardingInput) GetHeight() int64 {
	if o == nil || IsNil(o.Height) {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwardingInput) GetHeightOk() (*int64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ResponsesForwardingInput) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *ResponsesForwardingInput) SetHeight(v int64) {
	o.Height = &v
}

// GetReceived returns the Received field value if set, zero value otherwise.
func (o *ResponsesForwardingInput) GetReceived() string {
	if o == nil || IsNil(o.Received) {
		var ret string
		return ret
	}
	return *o.Received
}

// GetReceivedOk returns a tuple with the Received field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwardingInput) GetReceivedOk() (*string, bool) {
	if o == nil || IsNil(o.Received) {
		return nil, false
	}
	return o.Received, true
}

// HasReceived returns a boolean if a field has been set.
func (o *ResponsesForwardingInput) HasReceived() bool {
	if o != nil && !IsNil(o.Received) {
		return true
	}

	return false
}

// SetReceived gets a reference to the given string and assigns it to the Received field.
func (o *ResponsesForwardingInput) SetReceived(v string) {
	o.Received = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ResponsesForwardingInput) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwardingInput) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ResponsesForwardingInput) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *ResponsesForwardingInput) SetTime(v time.Time) {
	o.Time = &v
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *ResponsesForwardingInput) GetTxHash() *os.File {
	if o == nil || IsNil(o.TxHash) {
		var ret *os.File
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesForwardingInput) GetTxHashOk() (**os.File, bool) {
	if o == nil || IsNil(o.TxHash) {
		return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *ResponsesForwardingInput) HasTxHash() bool {
	if o != nil && !IsNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given *os.File and assigns it to the TxHash field.
func (o *ResponsesForwardingInput) SetTxHash(v *os.File) {
	o.TxHash = &v
}

func (o ResponsesForwardingInput) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesForwardingInput) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Chain) {
		toSerialize["chain"] = o.Chain
	}
	if !IsNil(o.Denom) {
		toSerialize["denom"] = o.Denom
	}
	if !IsNil(o.From) {
		toSerialize["from"] = o.From
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Received) {
		toSerialize["received"] = o.Received
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.TxHash) {
		toSerialize["tx_hash"] = o.TxHash
	}
	return toSerialize, nil
}

type NullableResponsesForwardingInput struct {
	value *ResponsesForwardingInput
	isSet bool
}

func (v NullableResponsesForwardingInput) Get() *ResponsesForwardingInput {
	return v.value
}

func (v *NullableResponsesForwardingInput) Set(val *ResponsesForwardingInput) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesForwardingInput) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesForwardingInput) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesForwardingInput(val *ResponsesForwardingInput) *NullableResponsesForwardingInput {
	return &NullableResponsesForwardingInput{value: val, isSet: true}
}

func (v NullableResponsesForwardingInput) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesForwardingInput) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


