/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"os"
	"time"
)

// checks if the ResponsesZkISM type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesZkISM{}

// ResponsesZkISM struct for ResponsesZkISM
type ResponsesZkISM struct {
	Creator *ResponsesShortAddress `json:"creator,omitempty"`
	ExternalId **os.File `json:"external_id,omitempty"`
	Groth16Vkey **os.File `json:"groth16_vkey,omitempty"`
	Height *int64 `json:"height,omitempty"`
	Id *int64 `json:"id,omitempty"`
	MerkleTreeAddress **os.File `json:"merkle_tree_address,omitempty"`
	State **os.File `json:"state,omitempty"`
	StateMembershipVkey **os.File `json:"state_membership_vkey,omitempty"`
	StateTransitionVkey **os.File `json:"state_transition_vkey,omitempty"`
	Time *time.Time `json:"time,omitempty"`
	TxHash **os.File `json:"tx_hash,omitempty"`
}

// NewResponsesZkISM instantiates a new ResponsesZkISM object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesZkISM() *ResponsesZkISM {
	this := ResponsesZkISM{}
	return &this
}

// NewResponsesZkISMWithDefaults instantiates a new ResponsesZkISM object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesZkISMWithDefaults() *ResponsesZkISM {
	this := ResponsesZkISM{}
	return &this
}

// GetCreator returns the Creator field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetCreator() ResponsesShortAddress {
	if o == nil || IsNil(o.Creator) {
		var ret ResponsesShortAddress
		return ret
	}
	return *o.Creator
}

// GetCreatorOk returns a tuple with the Creator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetCreatorOk() (*ResponsesShortAddress, bool) {
	if o == nil || IsNil(o.Creator) {
		return nil, false
	}
	return o.Creator, true
}

// HasCreator returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasCreator() bool {
	if o != nil && !IsNil(o.Creator) {
		return true
	}

	return false
}

// SetCreator gets a reference to the given ResponsesShortAddress and assigns it to the Creator field.
func (o *ResponsesZkISM) SetCreator(v ResponsesShortAddress) {
	o.Creator = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetExternalId() *os.File {
	if o == nil || IsNil(o.ExternalId) {
		var ret *os.File
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetExternalIdOk() (**os.File, bool) {
	if o == nil || IsNil(o.ExternalId) {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasExternalId() bool {
	if o != nil && !IsNil(o.ExternalId) {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given *os.File and assigns it to the ExternalId field.
func (o *ResponsesZkISM) SetExternalId(v *os.File) {
	o.ExternalId = &v
}

// GetGroth16Vkey returns the Groth16Vkey field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetGroth16Vkey() *os.File {
	if o == nil || IsNil(o.Groth16Vkey) {
		var ret *os.File
		return ret
	}
	return *o.Groth16Vkey
}

// GetGroth16VkeyOk returns a tuple with the Groth16Vkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetGroth16VkeyOk() (**os.File, bool) {
	if o == nil || IsNil(o.Groth16Vkey) {
		return nil, false
	}
	return o.Groth16Vkey, true
}

// HasGroth16Vkey returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasGroth16Vkey() bool {
	if o != nil && !IsNil(o.Groth16Vkey) {
		return true
	}

	return false
}

// SetGroth16Vkey gets a reference to the given *os.File and assigns it to the Groth16Vkey field.
func (o *ResponsesZkISM) SetGroth16Vkey(v *os.File) {
	o.Groth16Vkey = &v
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetHeight() int64 {
	if o == nil || IsNil(o.Height) {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetHeightOk() (*int64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *ResponsesZkISM) SetHeight(v int64) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ResponsesZkISM) SetId(v int64) {
	o.Id = &v
}

// GetMerkleTreeAddress returns the MerkleTreeAddress field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetMerkleTreeAddress() *os.File {
	if o == nil || IsNil(o.MerkleTreeAddress) {
		var ret *os.File
		return ret
	}
	return *o.MerkleTreeAddress
}

// GetMerkleTreeAddressOk returns a tuple with the MerkleTreeAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetMerkleTreeAddressOk() (**os.File, bool) {
	if o == nil || IsNil(o.MerkleTreeAddress) {
		return nil, false
	}
	return o.MerkleTreeAddress, true
}

// HasMerkleTreeAddress returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasMerkleTreeAddress() bool {
	if o != nil && !IsNil(o.MerkleTreeAddress) {
		return true
	}

	return false
}

// SetMerkleTreeAddress gets a reference to the given *os.File and assigns it to the MerkleTreeAddress field.
func (o *ResponsesZkISM) SetMerkleTreeAddress(v *os.File) {
	o.MerkleTreeAddress = &v
}

// GetState returns the State field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetState() *os.File {
	if o == nil || IsNil(o.State) {
		var ret *os.File
		return ret
	}
	return *o.State
}

// GetStateOk returns a tuple with the State field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetStateOk() (**os.File, bool) {
	if o == nil || IsNil(o.State) {
		return nil, false
	}
	return o.State, true
}

// HasState returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasState() bool {
	if o != nil && !IsNil(o.State) {
		return true
	}

	return false
}

// SetState gets a reference to the given *os.File and assigns it to the State field.
func (o *ResponsesZkISM) SetState(v *os.File) {
	o.State = &v
}

// GetStateMembershipVkey returns the StateMembershipVkey field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetStateMembershipVkey() *os.File {
	if o == nil || IsNil(o.StateMembershipVkey) {
		var ret *os.File
		return ret
	}
	return *o.StateMembershipVkey
}

// GetStateMembershipVkeyOk returns a tuple with the StateMembershipVkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetStateMembershipVkeyOk() (**os.File, bool) {
	if o == nil || IsNil(o.StateMembershipVkey) {
		return nil, false
	}
	return o.StateMembershipVkey, true
}

// HasStateMembershipVkey returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasStateMembershipVkey() bool {
	if o != nil && !IsNil(o.StateMembershipVkey) {
		return true
	}

	return false
}

// SetStateMembershipVkey gets a reference to the given *os.File and assigns it to the StateMembershipVkey field.
func (o *ResponsesZkISM) SetStateMembershipVkey(v *os.File) {
	o.StateMembershipVkey = &v
}

// GetStateTransitionVkey returns the StateTransitionVkey field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetStateTransitionVkey() *os.File {
	if o == nil || IsNil(o.StateTransitionVkey) {
		var ret *os.File
		return ret
	}
	return *o.StateTransitionVkey
}

// GetStateTransitionVkeyOk returns a tuple with the StateTransitionVkey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetStateTransitionVkeyOk() (**os.File, bool) {
	if o == nil || IsNil(o.StateTransitionVkey) {
		return nil, false
	}
	return o.StateTransitionVkey, true
}

// HasStateTransitionVkey returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasStateTransitionVkey() bool {
	if o != nil && !IsNil(o.StateTransitionVkey) {
		return true
	}

	return false
}

// SetStateTransitionVkey gets a reference to the given *os.File and assigns it to the StateTransitionVkey field.
func (o *ResponsesZkISM) SetStateTransitionVkey(v *os.File) {
	o.StateTransitionVkey = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *ResponsesZkISM) SetTime(v time.Time) {
	o.Time = &v
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *ResponsesZkISM) GetTxHash() *os.File {
	if o == nil || IsNil(o.TxHash) {
		var ret *os.File
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISM) GetTxHashOk() (**os.File, bool) {
	if o == nil || IsNil(o.TxHash) {
		return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *ResponsesZkISM) HasTxHash() bool {
	if o != nil && !IsNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given *os.File and assigns it to the TxHash field.
func (o *ResponsesZkISM) SetTxHash(v *os.File) {
	o.TxHash = &v
}

func (o ResponsesZkISM) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesZkISM) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Creator) {
		toSerialize["creator"] = o.Creator
	}
	if !IsNil(o.ExternalId) {
		toSerialize["external_id"] = o.ExternalId
	}
	if !IsNil(o.Groth16Vkey) {
		toSerialize["groth16_vkey"] = o.Groth16Vkey
	}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.MerkleTreeAddress) {
		toSerialize["merkle_tree_address"] = o.MerkleTreeAddress
	}
	if !IsNil(o.State) {
		toSerialize["state"] = o.State
	}
	if !IsNil(o.StateMembershipVkey) {
		toSerialize["state_membership_vkey"] = o.StateMembershipVkey
	}
	if !IsNil(o.StateTransitionVkey) {
		toSerialize["state_transition_vkey"] = o.StateTransitionVkey
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.TxHash) {
		toSerialize["tx_hash"] = o.TxHash
	}
	return toSerialize, nil
}

type NullableResponsesZkISM struct {
	value *ResponsesZkISM
	isSet bool
}

func (v NullableResponsesZkISM) Get() *ResponsesZkISM {
	return v.value
}

func (v *NullableResponsesZkISM) Set(val *ResponsesZkISM) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesZkISM) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesZkISM) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesZkISM(val *ResponsesZkISM) *NullableResponsesZkISM {
	return &NullableResponsesZkISM{value: val, isSet: true}
}

func (v NullableResponsesZkISM) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesZkISM) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


