/*
Celenium API

Celenium API is a powerful tool to access all blockchain data that is processed and indexed by our proprietary indexer. With Celenium API you can retrieve all historical data, off-chain data, blobs and statistics through our REST API. Celenium API indexer are open source, which allows you to not depend on third-party services. You can clone, build and run them independently, giving you full control over all components. If you have any questions or feature requests, please feel free to contact us. We appreciate your feedback!

API version: 1.0
Contact: celenium@pklabs.me
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package celenium

import (
	"encoding/json"
	"os"
	"time"
)

// checks if the ResponsesZkISMUpdate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ResponsesZkISMUpdate{}

// ResponsesZkISMUpdate struct for ResponsesZkISMUpdate
type ResponsesZkISMUpdate struct {
	Height *int64 `json:"height,omitempty"`
	Id *int64 `json:"id,omitempty"`
	NewState **os.File `json:"new_state,omitempty"`
	Signer *ResponsesShortAddress `json:"signer,omitempty"`
	Time *time.Time `json:"time,omitempty"`
	TxHash **os.File `json:"tx_hash,omitempty"`
}

// NewResponsesZkISMUpdate instantiates a new ResponsesZkISMUpdate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewResponsesZkISMUpdate() *ResponsesZkISMUpdate {
	this := ResponsesZkISMUpdate{}
	return &this
}

// NewResponsesZkISMUpdateWithDefaults instantiates a new ResponsesZkISMUpdate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewResponsesZkISMUpdateWithDefaults() *ResponsesZkISMUpdate {
	this := ResponsesZkISMUpdate{}
	return &this
}

// GetHeight returns the Height field value if set, zero value otherwise.
func (o *ResponsesZkISMUpdate) GetHeight() int64 {
	if o == nil || IsNil(o.Height) {
		var ret int64
		return ret
	}
	return *o.Height
}

// GetHeightOk returns a tuple with the Height field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISMUpdate) GetHeightOk() (*int64, bool) {
	if o == nil || IsNil(o.Height) {
		return nil, false
	}
	return o.Height, true
}

// HasHeight returns a boolean if a field has been set.
func (o *ResponsesZkISMUpdate) HasHeight() bool {
	if o != nil && !IsNil(o.Height) {
		return true
	}

	return false
}

// SetHeight gets a reference to the given int64 and assigns it to the Height field.
func (o *ResponsesZkISMUpdate) SetHeight(v int64) {
	o.Height = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *ResponsesZkISMUpdate) GetId() int64 {
	if o == nil || IsNil(o.Id) {
		var ret int64
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISMUpdate) GetIdOk() (*int64, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *ResponsesZkISMUpdate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given int64 and assigns it to the Id field.
func (o *ResponsesZkISMUpdate) SetId(v int64) {
	o.Id = &v
}

// GetNewState returns the NewState field value if set, zero value otherwise.
func (o *ResponsesZkISMUpdate) GetNewState() *os.File {
	if o == nil || IsNil(o.NewState) {
		var ret *os.File
		return ret
	}
	return *o.NewState
}

// GetNewStateOk returns a tuple with the NewState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISMUpdate) GetNewStateOk() (**os.File, bool) {
	if o == nil || IsNil(o.NewState) {
		return nil, false
	}
	return o.NewState, true
}

// HasNewState returns a boolean if a field has been set.
func (o *ResponsesZkISMUpdate) HasNewState() bool {
	if o != nil && !IsNil(o.NewState) {
		return true
	}

	return false
}

// SetNewState gets a reference to the given *os.File and assigns it to the NewState field.
func (o *ResponsesZkISMUpdate) SetNewState(v *os.File) {
	o.NewState = &v
}

// GetSigner returns the Signer field value if set, zero value otherwise.
func (o *ResponsesZkISMUpdate) GetSigner() ResponsesShortAddress {
	if o == nil || IsNil(o.Signer) {
		var ret ResponsesShortAddress
		return ret
	}
	return *o.Signer
}

// GetSignerOk returns a tuple with the Signer field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISMUpdate) GetSignerOk() (*ResponsesShortAddress, bool) {
	if o == nil || IsNil(o.Signer) {
		return nil, false
	}
	return o.Signer, true
}

// HasSigner returns a boolean if a field has been set.
func (o *ResponsesZkISMUpdate) HasSigner() bool {
	if o != nil && !IsNil(o.Signer) {
		return true
	}

	return false
}

// SetSigner gets a reference to the given ResponsesShortAddress and assigns it to the Signer field.
func (o *ResponsesZkISMUpdate) SetSigner(v ResponsesShortAddress) {
	o.Signer = &v
}

// GetTime returns the Time field value if set, zero value otherwise.
func (o *ResponsesZkISMUpdate) GetTime() time.Time {
	if o == nil || IsNil(o.Time) {
		var ret time.Time
		return ret
	}
	return *o.Time
}

// GetTimeOk returns a tuple with the Time field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISMUpdate) GetTimeOk() (*time.Time, bool) {
	if o == nil || IsNil(o.Time) {
		return nil, false
	}
	return o.Time, true
}

// HasTime returns a boolean if a field has been set.
func (o *ResponsesZkISMUpdate) HasTime() bool {
	if o != nil && !IsNil(o.Time) {
		return true
	}

	return false
}

// SetTime gets a reference to the given time.Time and assigns it to the Time field.
func (o *ResponsesZkISMUpdate) SetTime(v time.Time) {
	o.Time = &v
}

// GetTxHash returns the TxHash field value if set, zero value otherwise.
func (o *ResponsesZkISMUpdate) GetTxHash() *os.File {
	if o == nil || IsNil(o.TxHash) {
		var ret *os.File
		return ret
	}
	return *o.TxHash
}

// GetTxHashOk returns a tuple with the TxHash field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ResponsesZkISMUpdate) GetTxHashOk() (**os.File, bool) {
	if o == nil || IsNil(o.TxHash) {
		return nil, false
	}
	return o.TxHash, true
}

// HasTxHash returns a boolean if a field has been set.
func (o *ResponsesZkISMUpdate) HasTxHash() bool {
	if o != nil && !IsNil(o.TxHash) {
		return true
	}

	return false
}

// SetTxHash gets a reference to the given *os.File and assigns it to the TxHash field.
func (o *ResponsesZkISMUpdate) SetTxHash(v *os.File) {
	o.TxHash = &v
}

func (o ResponsesZkISMUpdate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ResponsesZkISMUpdate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Height) {
		toSerialize["height"] = o.Height
	}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	if !IsNil(o.NewState) {
		toSerialize["new_state"] = o.NewState
	}
	if !IsNil(o.Signer) {
		toSerialize["signer"] = o.Signer
	}
	if !IsNil(o.Time) {
		toSerialize["time"] = o.Time
	}
	if !IsNil(o.TxHash) {
		toSerialize["tx_hash"] = o.TxHash
	}
	return toSerialize, nil
}

type NullableResponsesZkISMUpdate struct {
	value *ResponsesZkISMUpdate
	isSet bool
}

func (v NullableResponsesZkISMUpdate) Get() *ResponsesZkISMUpdate {
	return v.value
}

func (v *NullableResponsesZkISMUpdate) Set(val *ResponsesZkISMUpdate) {
	v.value = val
	v.isSet = true
}

func (v NullableResponsesZkISMUpdate) IsSet() bool {
	return v.isSet
}

func (v *NullableResponsesZkISMUpdate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableResponsesZkISMUpdate(val *ResponsesZkISMUpdate) *NullableResponsesZkISMUpdate {
	return &NullableResponsesZkISMUpdate{value: val, isSet: true}
}

func (v NullableResponsesZkISMUpdate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableResponsesZkISMUpdate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


